//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrunler
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatis
    {
        public int SatısId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
